const details = [
    {
        src:require('./../assets/restraunt/DelhiHeights.jpg'),
        heading:'Delhi Heights',
        subHeading:'North Indian & South Indian',
        offer:'20%',
        ratings:'4.1',
        time:'30 mins',
        cost:'$170',
    },
    {
        src:require('./../assets/restraunt/chinaTown.jpg'),
        heading:'China Town',
        subHeading:'Chinese, Korean',
        offer:'20%',
        ratings:'4',
        time:'45 mins',
        cost:'$250',
    },
    {
        src:require('./../assets/restraunt/pizzaMania.jpg'),
        heading:'Pizza Mania',
        subHeading:'Pizza, Pasta, Chicken wings',
        offer:'25%',
        ratings:'3.9',
        time:'30 mins',
        cost:'$180',
    },
    {
        src:require('./../assets/restraunt/TacoCorner.jpg'),
        heading:'Taco Corner',
        subHeading:'Mexican',
        offer:'10%',
        ratings:'4',
        time:'45 mins',
        cost:'$350',
    },
    {
        src:require('./../assets/restraunt/saladmen.jpg'),
        heading:'Salad Men',
        subHeading:'Salad',
        offer:'5%',
        ratings:'4.5',
        time:'45 mins',
        cost:'$95',
    },
    {
        src:require('./../assets/restraunt/burgerPlaza.jpg'),
        heading:'Burger Plaza',
        subHeading:'Fast food, Pizza, Burger, Fries',
        offer:'25%',
        ratings:'3.8',
        time:'30 mins',
        cost:'$225',
    },
    {
        src:require('./../assets/restraunt/BrunosFriedChicken.jpg'),
        heading:'Brunos Fried Chicken',
        subHeading:'Fast food, Fried Chicken',
        offer:'25%',
        ratings:'4',
        time:'30 mins',
        cost:'$200',
    },
    {
        src:require('./../assets/restraunt/ShenaazsBakery.jpg'),
        heading:'Shehnaaz Bakery',
        subHeading:'Cakes, Desserts, Pastries',
        offer:'15%',
        ratings:'4.2',
        time:'50 mins',
        cost:'$125',
    }
];

export default details;